/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sqduajbczbvaxtucclzf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZHVhamJjemJ2YXh0dWNjbHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3ODAxNDMsImV4cCI6MjA5MzM1NjE0M30.ZU-y54Vns-AeMGZwLbbszcb2MXW6sLhgM4NU1l5zG8k"